version: "3.8"

services:
  backend:
    build: ./Backend
    container_name: todolist-backend
    restart: always
    env_file:
      - ./Backend/.env
    ports:
      - "3000:3000"

  frontend:
    build: ./Frontend/TodoListFront
    container_name: todolist-frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
